[project]
name = "paymo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
    "redis>=6.2.0",
]

[tool.uv.workspace]
members = [
    "gateway",
    "wise",
]
